// ─── llm/mock.rs ──────────────────────────────────────────────────────────────
// Mock inference: keyword-matching responses + jam variation, no real model needed.

use anyhow::Result;
use crossbeam_channel::{Receiver, Sender};
use parking_lot::RwLock;
use std::sync::Arc;

use crate::state::{AppState, apply_llm_update};

use super::{LlmInput, LlmOutput, instructions};

/// Generate a plausible JSON response for testing without a real model.
/// Comments are intentionally terse — personality is generated by the real LLM
/// from the system prompt; there is no point faking it in mock mode.
pub fn mock_response(prompt: &str, heat: f32) -> Result<LlmOutput> {
    let prompt_lower = prompt.to_lowercase();

    // Instruction set takes priority — handles all specific add/remove commands
    // and named presets. Falls through to jam-variation when nothing matches.
    if let Some(inst) = instructions::InstructionSet::get().find_best_match(&prompt_lower) {
        let mut json = inst.params.clone();
        if json.get("_comment").is_none() {
            json["_comment"] = serde_json::json!(inst.comment);
        }
        return Ok(LlmOutput {
            text: serde_json::to_string_pretty(&json).unwrap_or_default(),
            param_update: Some(json),
            tokens_per_sec: 42.0,
            prompt_tokens: 0,
            completion_tokens: 0,
            context_used: 256,
            is_jam: false,
            thinking: None,
            mc_line: None,
            before_state: None,
        });
    }

    let json = if prompt_lower.contains("acid") {
        serde_json::json!({
            "_comment": "acid — bass resonance + env_mod up, short decay",
            "bass": { "cutoff": 0.5, "resonance": 0.70, "env_mod": 0.80, "decay": 0.38, "distortion": 0.05, "volume": 0.9 },
            "sequencer": { "bpm": 135.0 },
            "fx": { "distortion_drive": 0.0, "distortion_mix": 0.0, "delay_time": 0.3, "delay_feedback": 0.35, "delay_mix": 0.15 }
        })
    } else if prompt_lower.contains("dark") || prompt_lower.contains("deep") {
        serde_json::json!({
            "_comment": "dark — filter cutoff down, reverb + delay up",
            "bass": { "cutoff": 0.15, "resonance": 0.5, "env_mod": 0.3 },
            "fx": { "reverb_size": 0.8, "reverb_mix": 0.5, "delay_mix": 0.3 }
        })
    } else if prompt_lower.contains("fast")
        || prompt_lower.contains("hard")
        || prompt_lower.contains("harder")
    {
        serde_json::json!({
            "_comment": "harder — decay tighter, distortion drive up",
            "bass": { "decay": 0.2, "distortion": 0.12, "env_mod": 0.85 },
            "fx": { "distortion_drive": 0.15, "distortion_mix": 0.3 }
        })
    } else if prompt_lower.contains("mellow")
        || prompt_lower.contains("chill")
        || prompt_lower.contains("softer")
        || prompt_lower.contains("quieter")
    {
        serde_json::json!({
            "_comment": "softer — filter open, resonance back, volume down",
            "bass": { "cutoff": 0.6, "resonance": 0.3, "env_mod": 0.25, "volume": 0.75 },
            "fx": { "reverb_mix": 0.3, "delay_mix": 0.2 }
        })
    } else if prompt_lower.contains("melody")
        || prompt_lower.contains("notes")
        || prompt_lower.contains("bass line")
        || prompt_lower.contains("bassline")
        || prompt_lower.contains("clap")
        || prompt_lower.contains("snare")
        || prompt_lower.contains("hihat")
        || prompt_lower.contains("hi-hat")
        || prompt_lower.contains("hat")
        || prompt_lower.contains("kick")
        || prompt_lower.contains("pattern")
    {
        // Pattern requests require the real model — mock mode can only nudge knobs.
        serde_json::json!({
            "_comment": "pattern/rhythm request — needs real model; nudging filter in mock mode",
            "bass": { "env_mod": (0.4 + heat * 0.3).clamp(0.2, 0.95) }
        })
    } else if prompt_lower.contains("reverb")
        || prompt_lower.contains("space")
        || prompt_lower.contains("room")
        || prompt_lower.contains("atmosphere")
    {
        serde_json::json!({
            "_comment": "reverb + delay up for depth and space",
            "fx": { "reverb_mix": 0.3, "reverb_size": 0.6, "delay_mix": 0.18, "delay_feedback": 0.4 }
        })
    } else if prompt_lower.contains("delay") || prompt_lower.contains("echo") {
        serde_json::json!({
            "_comment": "dotted-eighth delay",
            "fx": { "delay_time": 0.375, "delay_feedback": 0.45, "delay_mix": 0.25 }
        })
    } else if prompt_lower.contains("distort")
        || prompt_lower.contains("drive")
        || prompt_lower.contains("grit")
    {
        serde_json::json!({
            "_comment": "master bus saturation up",
            "fx": { "distortion_drive": 0.25, "distortion_mix": 0.4 }
        })
    } else if prompt_lower.contains("no fx")
        || prompt_lower.contains("dry")
        || prompt_lower.contains("clean")
    {
        serde_json::json!({
            "_comment": "all FX cleared",
            "fx": { "reverb_mix": 0.0, "delay_mix": 0.0, "distortion_mix": 0.0, "distortion_drive": 0.0 }
        })
    } else if prompt_lower.contains("simpler")
        || prompt_lower.contains("strip")
        || prompt_lower.contains("minimal")
    {
        serde_json::json!({
            "_comment": "FX stripped back",
            "fx": { "reverb_mix": 0.0, "delay_mix": 0.0 }
        })
    } else {
        // Jam mode — heat controls how dramatic the mutation is
        let ms = std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .unwrap_or_default()
            .subsec_millis() as f32;
        let p1 = ms / 1000.0;
        let p2 = ms * 1.7 / 1000.0;
        let p3 = ms * 0.4 / 1000.0;
        let sweep = heat * 0.5 + 0.05;
        let cut = (0.3 + (p1 * 2.7).sin().abs() * sweep * 1.6).clamp(0.15, 0.95);
        let res = (0.45 + (p2 * 1.9).cos() * sweep).clamp(0.2, 0.95);

        if heat < 0.3 {
            serde_json::json!({
                "_comment": "filter nudge",
                "bass": { "cutoff": cut, "resonance": res }
            })
        } else if heat < 0.6 {
            let bpm_shift = (p3.sin() * heat * 12.0) as i32;
            serde_json::json!({
                "_comment": "filter + bpm nudge",
                "bass": { "cutoff": cut, "resonance": res,
                           "env_mod": (0.5 + (p2 * 0.8).sin() * sweep).clamp(0.2, 0.95) },
                "sequencer": { "bpm": (130.0 + bpm_shift as f32).clamp(100.0, 160.0) }
            })
        } else if heat < 0.85 {
            let bpm = (125.0 + (p3 * 2.0).sin() * heat * 20.0).clamp(110.0, 155.0);
            serde_json::json!({
                "_comment": "filter + bpm push",
                "bass": { "cutoff": cut, "resonance": res,
                           "env_mod": (0.6 + (p1 * 1.1).cos() * sweep).clamp(0.3, 0.95),
                           "decay": (0.3 + (p2 * 0.5).sin().abs() * 0.4).clamp(0.15, 0.8) },
                "sequencer": { "bpm": bpm }
            })
        } else {
            let styles: &[(&str, f32, f32, f32, f32)] = &[
                ("full acid — resonance + chaos up", 0.2, 0.88, 0.85, 148.0),
                ("dark + slow — filter down, BPM down", 0.7, 0.40, 0.30, 95.0),
                ("hard + fast — filter sweep, BPM up", 0.5, 0.65, 0.70, 160.0),
                ("hypnotic — mid filter, lower BPM", 0.6, 0.55, 0.50, 118.0),
            ];
            let (cmt, cut2, res2, env2, bpm2) = styles[((ms * 0.003) as usize) % styles.len()];
            serde_json::json!({
                "_comment": cmt,
                "bass": { "cutoff": cut2, "resonance": res2, "env_mod": env2 },
                "sequencer": { "bpm": bpm2 }
            })
        }
    };

    Ok(LlmOutput {
        text: serde_json::to_string_pretty(&json).unwrap_or_default(),
        param_update: Some(json),
        tokens_per_sec: 42.0, // mock speed
        prompt_tokens: 0,
        completion_tokens: 0,
        context_used: 256,
        is_jam: false,
        thinking: None,
        mc_line: None,
        before_state: None,
    })
}

/// Runs when --mock is explicitly passed.  Handles inference with `mock_response`
/// and model-switch no-ops.  Never exits unless the channel closes.
pub fn run_mock_loop(
    state: Arc<RwLock<AppState>>,
    input_rx: Receiver<LlmInput>,
    output_tx: Sender<LlmOutput>,
) {
    while let Ok(input) = input_rx.recv() {
        if let LlmInput::SwitchModel(ref new_path) = input {
            log::warn!(
                "Mock mode: model switch to '{}' ignored (no real backend)",
                new_path
            );
            continue;
        }

        let LlmInput::Infer {
            ref prompt,
            one_shot,
        } = input
        else {
            continue;
        };

        let heat = state.read().llm.heat;
        {
            let mut s = state.write();
            s.llm.is_inferring = true;
            s.llm.last_prompt = prompt.clone();
        }

        match mock_response(prompt, heat) {
            Ok(output) => {
                if let Some(ref update) = output.param_update {
                    let current = state.read().clone();
                    let next = apply_llm_update(current, update);
                    *state.write() = next;
                    let comment = update
                        .get("_comment")
                        .and_then(|v| v.as_str())
                        .unwrap_or("[mock]");
                    let persona = state.read().llm.persona_name.clone();
                    if one_shot {
                        log::info!("{} (mock) -> {}", persona, comment);
                    }
                }
                {
                    let mut s = state.write();
                    s.llm.is_inferring = false;
                    s.llm.tokens_per_sec = output.tokens_per_sec;
                    s.llm.last_response = output.text.clone();
                }
                let mut output = output;
                output.is_jam = !one_shot;
                let _ = output_tx.try_send(output);
                if !one_shot {
                    let _ = input_rx.try_recv();
                    let _ = output_tx.send(LlmOutput {
                        text: "[jam_cycle_done]".to_string(),
                        param_update: None,
                        tokens_per_sec: 0.0,
                        prompt_tokens: 0,
                        completion_tokens: 0,
                        context_used: 0,
                        is_jam: true,
                        thinking: None,
                        mc_line: None,
                        before_state: None,
                    });
                }
            }
            Err(e) => {
                log::error!("Mock inference error: {}", e);
                state.write().llm.is_inferring = false;
            }
        }
    }
    log::info!("Mock LLM loop exiting");
}
