// ─── audio/dsp/lfo_target_opcode.rs ───────────────────────────────────────────
// `lfo_target_to_u8` lookup table — encodes `LfoTarget` into a
// compact u8 opcode consumed by the audio thread.  Extracted from
// `params.rs` to keep that file under the 1000-line cap; the
// opcode table grows with every new modulation target.
//
// Stable IDs — adding new targets requires adding a new code in
// the match below AND a matching arm in `apply_mod_target`
// (src/audio/dsp/mod_apply.rs).  The two tables are kept in
// lock-step manually; tests in `dsp_mod_apply_tests` cover the
// round-trip.

use crate::state::LfoTarget;

pub fn lfo_target_to_u8(t: LfoTarget) -> u8 {
    use LfoTarget::*;
    match t {
        None => 0,
        // Legacy (1..16) — drive the existing LFO-module path.
        BassCutoff => 1,
        BassResonance => 2,
        BassPitch => 3,
        BassVolume => 4,
        ReverbMix => 5,
        DelayTime => 6,
        DelayFeedback => 7,
        ChorusMix => 8,
        ChorusRate => 9,
        Kick808Pitch => 10,
        PhaserRate => 11,
        PhaserDepth => 12,
        DistortionDrive => 13,
        MasterVolume => 14,
        An1xCutoff => 15,
        An1xPitch => 16,
        // Pan family.
        BassPan => 17,
        HooverPan => 18,
        NoisePan => 19,
        Kick808Pan => 20,
        Snare808Pan => 21,
        Hihat808Pan => 22,
        Kick909Pan => 23,
        Snare909Pan => 24,
        Hihat909Pan => 25,
        Clap909Pan => 26,
        An1xPan => 27,
        // FX knob expansion.
        ReverbSize => 28,
        ReverbDamp => 29,
        DelayMix => 30,
        ChorusDepth => 31,
        PhaserMix => 32,
        WaveshaperDrive => 33,
        WaveshaperMix => 34,
        DistortionMix => 35,
        BitcrushBits => 36,
        BitcrushRate => 37,
        BitcrushMix => 38,
        RingModFreq => 39,
        RingModMix => 40,
        EqLow => 41,
        EqMid => 42,
        EqHigh => 43,
        CompThresh => 44,
        CompRatio => 45,
        CompMix => 46,
        TapeDrive => 47,
        TapeMix => 48,
        TapeFlutter => 49,
        AutotuneAmount => 50,
        AutotuneMix => 51,
        // Drum extras (52..62) and sampler/granular (63..69).
        Kick808Decay => 52,
        Snare808Tone => 53,
        Snare808Decay => 54,
        Kick909Pitch => 55,
        Kick909Decay => 56,
        Snare909Tone => 57,
        Snare909Decay => 58,
        Clap909Decay => 59,
        AmenVolume => 60,
        AmenStart => 61,
        AmenGate => 62,
        GranularVolume => 63,
        GranularDensity => 64,
        GranularGrain => 65,
        GranularPos => 66,
        StereoWidth => 67,
        GabberKickPitch => 68,
        GabberKickDecay => 69,
        GabberKickClip => 70,
        GabberKickPan => 71,
        NeuTtsVolume => 72,
        FlangerRate => 73,
        FlangerDepth => 74,
        FlangerFeedback => 75,
        FlangerMix => 76,
        LimiterThreshold => 77,
        LimiterCeiling => 78,
        LimiterRelease => 79,
        LimiterLookahead => 80,
        SvfCutoff => 81,
        SvfResonance => 82,
        SvfDrive => 83,
        SvfMix => 84,
        CombPitch => 85,
        CombFeedback => 86,
        CombDamp => 87,
        CombMix => 88,
        TiltTilt => 89,
        TiltPivot => 90,
        TiltMix => 91,
        TransientAttack => 92,
        TransientSustain => 93,
        TransientMix => 94,
        ExciterAmount => 95,
        ExciterFreq => 96,
        ExciterMix => 97,
        MultitapTime => 98,
        MultitapSpread => 99,
        MultitapFeedback => 100,
        MultitapMix => 101,
        RevDelayTime => 102,
        RevDelayFeedback => 103,
        RevDelayMix => 104,
        TapeStopMix => 105,
        StutterRate => 106,
        StutterSlice => 107,
        StutterMix => 108,
        FreezeMix => 109,
        GateThreshold => 110,
        GateAttack => 111,
        GateRelease => 112,
        GateDepth => 113,
        GateMix => 114,
        VocoderBands => 115,
        VocoderCarrierMix => 116,
        VocoderSense => 117,
        VocoderMix => 118,
        WidenHaas => 119,
        WidenSide => 120,
        WidenMix => 121,
        FreqShiftAmount => 122,
        FreqShiftFeedback => 123,
        FreqShiftMix => 124,
        SampleVolume => 125,
        SamplePan => 126,
        SamplePitch => 127,
        SampleCutoff => 128,
    }
}
